import { createClient, SupabaseClient } from '@supabase/supabase-js';

const STORAGE_KEY_URL = 'soe_haru_custom_supabase_url';
const STORAGE_KEY_KEY = 'soe_haru_custom_supabase_anon_key';
const STORAGE_KEY_TABLE = 'soe_haru_table_name';

// Default existing project credentials provided previously by user
export const EXISTING_PROJECT_URL = 'https://vyrmeihqaljugjnysbxs.supabase.co';
export const EXISTING_PROJECT_KEY = 'sb_publishable_OfHSvklftlzryhEJbbNsCg_hNAKvWhU';

export function getSupabaseConfig(): { url: string; anonKey: string; isCustom: boolean; tableName: string } {
  try {
    const savedUrl = localStorage.getItem(STORAGE_KEY_URL);
    const savedKey = localStorage.getItem(STORAGE_KEY_KEY);
    const savedTable = localStorage.getItem(STORAGE_KEY_TABLE) || 'comments_soe_haru';
    if (savedUrl && savedKey) {
      return { url: savedUrl, anonKey: savedKey, isCustom: true, tableName: savedTable };
    }
  } catch {}

  const envUrl = (import.meta as any).env?.VITE_SUPABASE_URL;
  const envKey = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY;
  if (envUrl && envKey) {
    return { url: envUrl, anonKey: envKey, isCustom: true, tableName: 'comments_soe_haru' };
  }

  // Default to existing project using separate table comments_soe_haru
  return {
    url: EXISTING_PROJECT_URL,
    anonKey: EXISTING_PROJECT_KEY,
    isCustom: true,
    tableName: 'comments_soe_haru',
  };
}

export function saveSupabaseConfig(url: string, anonKey: string, tableName = 'comments_soe_haru') {
  try {
    if (url && anonKey) {
      localStorage.setItem(STORAGE_KEY_URL, url.trim());
      localStorage.setItem(STORAGE_KEY_KEY, anonKey.trim());
      localStorage.setItem(STORAGE_KEY_TABLE, tableName.trim());
    } else {
      localStorage.removeItem(STORAGE_KEY_URL);
      localStorage.removeItem(STORAGE_KEY_KEY);
      localStorage.removeItem(STORAGE_KEY_TABLE);
    }
    reinitSupabaseClient();
  } catch (e) {
    console.error('Failed to save Supabase config:', e);
  }
}

let activeClient: SupabaseClient | null = null;

function reinitSupabaseClient(): SupabaseClient | null {
  const { url, anonKey } = getSupabaseConfig();
  if (url && anonKey) {
    try {
      activeClient = createClient(url, anonKey, {
        auth: { persistSession: false, autoRefreshToken: false }
      });
      return activeClient;
    } catch (err) {
      console.error('Invalid Supabase configuration:', err);
      activeClient = null;
      return null;
    }
  }
  activeClient = null;
  return null;
}

export function getSupabase(): SupabaseClient | null {
  if (!activeClient) {
    return reinitSupabaseClient();
  }
  return activeClient;
}

export function getCommentsTableName(): string {
  const { tableName } = getSupabaseConfig();
  return tableName || 'comments_soe_haru';
}

export function getPresenceTableName(): string {
  const { tableName } = getSupabaseConfig();
  return tableName === 'comments' ? 'presence_log' : 'presence_soe_haru';
}

export const SQL_SCHEMA_SINGLE_PROJECT = `-- ==========================================================
-- CARA MENGGUNAKAN 1 PROJECT SUPABASE UNTUK SOE & HARU
-- Cukup jalankan skrip ini di SQL Editor project Supabase kamu
-- ==========================================================

-- 1. Buat tabel comments_soe_haru (terpisah dari tabel comments lama)
create table if not exists public.comments_soe_haru (
  id bigint generated by default as identity primary key,
  name text not null,
  message text default '',
  viewonce_photo text,
  viewonce_opened boolean default false,
  reply_name text,
  reply_message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Buat tabel presence_soe_haru (status online & last seen Soe & Haru)
create table if not exists public.presence_soe_haru (
  identity text primary key,
  last_seen timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Aktifkan Keamanan Row Level Security (RLS) & Kebijakan Akses
alter table public.comments_soe_haru enable row level security;
alter table public.presence_soe_haru enable row level security;

create policy "Allow all read comments_soe_haru" on public.comments_soe_haru for select using (true);
create policy "Allow all insert comments_soe_haru" on public.comments_soe_haru for insert with check (true);
create policy "Allow all update comments_soe_haru" on public.comments_soe_haru for update using (true);

create policy "Allow all read presence_soe_haru" on public.presence_soe_haru for select using (true);
create policy "Allow all upsert presence_soe_haru" on public.presence_soe_haru for all using (true);

-- 4. Aktifkan Realtime otomatis
alter publication supabase_realtime add table public.comments_soe_haru;
alter publication supabase_realtime add table public.presence_soe_haru;

-- 5. Buat Storage Bucket 'photos' untuk menyimpan Foto Sekali Lihat
insert into storage.buckets (id, name, public) 
values ('photos', 'photos', true)
on conflict (id) do nothing;

create policy "Allow all read photos" on storage.objects for select using (bucket_id = 'photos');
create policy "Allow all insert photos" on storage.objects for insert with check (bucket_id = 'photos');
create policy "Allow all delete photos" on storage.objects for delete using (bucket_id = 'photos');
`;
